### ISSUE TITLE
Entrega Trabajo Práctico N° 1

### ISSUE THREAD

**Issue by LiahNa** [CapriLucas/2020_k2002_Grupo_8#1]
Solicitamos la corrección del trabajo práctico: @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

Excelente trabajo. Impecable. Felicitaciones ! =D
Lo estuve revisando, pero por el momento no tengo comentarios para realizarles.

Nota: 10

@LiahNa @dhuallpa @cami-forconi @AracelyAmaro  @CapriLucas @MatFernandez
