### ISSUE TITLE
Entrega Trabajo Práctico N° 2 

### ISSUE THREAD

**Issue by LiahNa** [CapriLucas/2020_k2002_Grupo_8#2]
Solicito la revisión del trabajo práctico : @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Excelente trabajo equipo !

Impecable
Nota 10

El único detalle, es que tuve que ingresar C mayúscula para ingresar otra expresión. Con "c" minúscula no me lo tomó.

Pero muy bien como gestionaron los mensajes de error.

Saludos,

Santiago

@LiahNa @dhuallpa @cami-forconi @AracelyAmaro
