### ISSUE TITLE
Entrega Trabajo Practico Nº3

### ISSUE THREAD

**Issue by MatFernandez** [CapriLucas/2020_k2002_Grupo_8#3]
Solicitamos la revisión del trabajo práctico : @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados excelente trabajo ! Felicitaciones. Lindo el menú =)

Una cosa, el operador "?" es un operador ternario que le sigue en procedencia a la asignación. Creo que se los está tomando como un caracter no reconocido. El único detalle, el resto un bárbaro.

Nota: 10

Saludos
