### ISSUE TITLE
To do list tp 4

### ISSUE THREAD

**Issue by CapriLucas** [CapriLucas/2020_k2002_Grupo_8#4]
**1)** Crear y copiar un .txt las gramaticas de declaraciones y sentencias (Cada una en un txt aparte)
usar la del libro combinada con la del campus virtual.
**2)** probar los ejemplos asi se van familiarizando con lo que tenemos que hacer con bison y flex
comandos para ejecutar 

> **a)flex** archivo.l 
>  **b)** bison -d archivo.y
>  Bison les crea el archivo.tab.c y archivo.tab.h
>  Flex les crea lex.yy.c
>  **c)** gcc archivo.tab.c lex.yy.c
>  Esto les crea el a.exe 
>  **d)** a.exe

Nota1: No probar TP4.l y TP4.y no esta para compilar 
Nota2: No compila? Puede ser:

>  **a)** por que la carpeta Flex y Bison tiene espacios en el nombre
>  Cambiarlo de Flex y Bison -> FlexyBison o Flex_y_Bison (cambiar nombre en el winrar, descomprimirlo y ubicarlo en
>  el disco C, no olvidarse cambiarlo en el PATH tambien), despues reiniciar PC o VSCODE(si lo usaste tarda un poco).
>  **b)** si en el error incluye #include <y.tab.h> si tira esto hay que borrar ese include en donde aparezca
>  **c)** agregar el #include "archivo.tab.h" en archivo.l

**3)** Completar en TP4.l las acciones de las reglas y agregar su return a %token(en TP4.y) segun su 
tipo de dato descripto en %union
**4)** Crear una funcion parecida a la del tp3 que devuelva y presente opciones de lo que pide el tp (que 
no devuelva nada todavia pero que tenga un lugar en donde poner la funcion que va a devolver ) 
en funciones.h
**5)** Una vez hecho el (1) realizar sus reglas gramaticales como la que se hizo en expresiones
**6)** Una vez hecho el (2) (3) realizar un chequeo de las reglas y definiciones a detalle del TP4.l y TP4.y
**7)** Ver todo el video "completo" de bison parte 1,2,de bison debug y demas. Sacar conclusiones de como 
mejorar/facilitar el tp, si es posible anotarlo a detalle.(De la clase de los lunes tambien) 
**8)** Crear las acciones de expresiones (codigo en funciones.h)
**9)** Crear las acciones de declaraciones (codigo en funciones.h)
**10)** Crear las acciones de sentencias (codigo en funciones.h)
Nota: No correr el programa hasta tener el paso (5 y 6)

**Comment by CapriLucas** [comment]
**DUDAS GRAMATICA PARA SENTENCIAS**
Buenas, estuve haciendo la gramatica y me saltaron algunas dudas que tal vez ustedes ya la tienen clara.

1. Tengo que formar esta produccion haciendo referencia al if, else, etc. y como todos estos son palabras reservadas pertenecen al mismo token en el archivo ".l". Queria saber si se les ocurria como resolverlo.

`sentSelecc:   "if" '(' exp ')' sent
            | "if" '(' exp ')' sent "else" sent
            | "switch" '(' exp ')' sent`

2. En varias producciones aparecen no-terminales con el simbolo de opcional, asi: 
![image](https://user-images.githubusercontent.com/62937251/94136253-0b0abc80-fe3b-11ea-8853-56c1c3669662.png)
Por ahora no se como resolver esto y lo deje en el archivo marcado con un signo '?'

**Comment by dhuallpa** [comment]
1. (ARREGLAR FUNCION de opciones SON 6 OPCIONES (1)(2)(3)(4): lo que pide el tp, (5) reporte completo, 
 la (6) que permita salir del programa) y que si elige un nro cualquiera muestre msj de error 
 y reinicie la seleccion de opciones hasta que lo haga correctamente. 

2. Chequear reglas de declaraciones, omiti algunas(pregunten si tienen dudas).

3. Poner el input en sentencias (creo que ahi inicia?) 
4. Empezar a hacer las acciones expresiones una vez creadas todas las listas.

**Comment by dhuallpa** [comment]
- ARREGLAR FUNCION de opciones SON 6 OPCIONES (1)(2)(3)(4): lo que pide el tp, (5) reporte completo, la (6) que permita salir del programa) y que si elige un nro cualquiera muestre msj de error y reinicie la seleccion de opciones hasta que lo haga correctamente.

- Chequear reglas de declaraciones, omiti algunas(pregunten si tienen dudas).

- Poner el input en sentencias y ordenar las gramaticas en sentencia-declaracion-expresion luego revisar que las derivaciones
esten completas.

- Empezar a hacer las acciones expresiones una vez creadas todas las listas.

- Crear un gestionador de errores(dos funciones distintas) sintacticos y uno de semanticos (con un switch y en cada case de valor 0 ... n  que imprima un error diferente, se le debe pasar por parametro un nro entero ) 

- aplicar tabla de simbolos para el tp.

- buscar errores semanticos y sintacticos posibles y agregarlos al gestionador de errores.

**Comment by MatFernandez** [comment]
- En vez de hacer opciones y complicarnos mucho con listas, creo que lo mejor va a ser que imprima el reporte por pantalla y lo guarde en un Salida.txt. Lo mismo con la tabla de simbolos, creo que seria mejor dejarlo para el integrador.

- Revise la gramatica, le corregi un par de cosas que tenia mal y saque las Definiciones Externas que (la complicaban mucho para la lectura y para la compilacion)

- En el archivo.l, ordené las reglas para que no haya conflictos 

- Hice una prueba leyendo del Entrada.txt, y salta el yyerror  (no entiendo por que, porque en teoria la gramatica esta bien, deberia emparejar alguna de las reglas, el archivo Entrada.txt solamente tiene un int a = 4;).

- Faltan agregar algunos printf y agregar un token Error para la parte de la gramatica.

**Comment by MatFernandez** [comment]
Modifique la gramatica para que sea mas simple y entendible.

Revisar el archivo .l porque no imprime ningun printf del .y, (no tira ningun error de la gramatica por ahora). 
Es raro, debe haber alguna regla mal ordenada en el .l . Probe agregando el token error vinculado a la ultima regla "comodin", tira siempre error, asi que debe ser de eso).
